{% set name = "ringtail" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ringtail-{{ version }}.tar.gz
  sha256: 0acc8108c4b8a4208bfd13f0c254de5f7310038329aa3e90d99f1cbbeab8a4b5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  entry_points:
    - rt_process_vs=ringtail.cli.rt_process_vs:main
    - rt_compare=ringtail.cli.rt_compare:main
    - rt_db_v100_to_v110=ringtail.cli.rt_db_v100_to_v110:main
    - rt_db_to_v200=ringtail.cli.rt_db_to_v200:main
    - rt_generate_config_file=ringtail.cli.rt_generate_config_file:main

requirements:
  host:
    - python >=3.9
    - setuptools >=61.0
    - pip
  run:
    - python >=3.9
    - meeko ==0.5.1
    - rdkit
    - scipy
    - matplotlib-base
    - pandas
    - multiprocess
    - chemicalite
    - pytest


test:
  imports:
    - ringtail
  commands:
    - pip check
    - rt_process_vs --help
    - rt_compare --help
    - rt_db_v100_to_v110 --help
    - rt_db_to_v200 --help
    - rt_generate_config_file --help
  requires:
    - pip

about:
  home: https://github.com/forlilab/Ringtail
  summary: Package for creating database from virtual screening files and performing filtering on results.
  license: LGPL-2.1-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - nbruciaferri
    - diogomart
    - maylinnp
